#define PI 3.1415926535897932384626433832795f
#define UNIT PI / 1024.0f

#define TILE_SIZE 128
#define PLANE_HEIGHT 256

#define CAMERA_BUFFER_BINDING_ID 0
#define LIGHT_BUFFER_BINDING_ID 1
#define MODEL_BUFFER_IN_BINDING_ID 2
#define VERTEX_BUFFER_OUT_BINDING_ID 3
#define VERTEX_BUFFER_IN_BINDING_ID 4
#define TEMP_VERTEX_BUFFER_IN_BINDING_ID 5
#define TEXTURE_BUFFER_OUT_BINDING_ID 6
#define TEXTURE_BUFFER_IN_BINDING_ID 7
#define TEMP_TEXTURE_BUFFER_IN_BINDING_ID 8
#define NORMAL_BUFFER_OUT_BINDING_ID 9
#define NORMAL_BUFFER_IN_BINDING_ID 10
#define TEMP_NORMAL_BUFFER_IN_BINDING_ID 11

#define FOG_SCENE_EDGE_MIN ((-expandedMapLoadingChunks * 8 + 1) * TILE_SIZE)
#define FOG_SCENE_EDGE_MAX ((104 + expandedMapLoadingChunks * 8 - 1) * TILE_SIZE)
#define FOG_CORNER_ROUNDING 20
#define FOG_CORNER_ROUNDING_SQUARED (FOG_CORNER_ROUNDING * FOG_CORNER_ROUNDING)

#define FIRE_CAPE 41
#define INFERNAL_CAPE 60

#define MAX_Z_HEIGHT 4 // 4 tiles high
#define MAX_SHADOW_DISTANCE 100 // 100 tiles.

#define LIGHT_TYPE_INVALID 0
#define LIGHT_TYPE_DIRECTIONAL 1
#define LIGHT_TYPE_POINT 2
#define LIGHT_TYPE_SPOT 3

#define LIGHT_ANIM_NONE 0
#define LIGHT_ANIM_FLICKER 1
#define LIGHT_ANIM_PULSE 2


