#define PI 3.1415926535897932384626433832795f
#define UNIT PI / 1024.0f

#define TILE_SIZE 128
#define PLANE_HEIGHT 256
#define EXTENDED_SCENE_SIZE 184
#define SCENE_SIZE 104
#define SCENE_OFFSET 40

#define VPOS_BINDING_ID 0
#define VHSL_BINDING_ID 1
#define VUV_BINDING_ID 2
#define VNORM_BINDING_ID 3
#define VFLAGS_BINDING_ID 4

#define CAMERA_BUFFER_BINDING_ID 0
#define PLAYER_BUFFER_BINDING_ID 1
#define ENVIRONMENT_BUFFER_BINDING_ID 2
#define TILEMARKER_BUFFER_BINDING_ID 3
#define SYSTEMINFO_BUFFER_BINDING_ID 4
#define CONFIG_BUFFER_BINDING_ID 5

#define MODEL_BUFFER_IN_BINDING_ID 1
#define VERTEX_BUFFER_OUT_BINDING_ID 2
#define VERTEX_BUFFER_IN_BINDING_ID 3
#define TEMP_VERTEX_BUFFER_IN_BINDING_ID 4
#define TEXTURE_BUFFER_OUT_BINDING_ID 5
#define TEXTURE_BUFFER_IN_BINDING_ID 6
#define TEMP_TEXTURE_BUFFER_IN_BINDING_ID 7
#define NORMAL_BUFFER_OUT_BINDING_ID 8
#define NORMAL_BUFFER_IN_BINDING_ID 9
#define TEMP_NORMAL_BUFFER_IN_BINDING_ID 10
#define FLAGS_BUFFER_OUT_BINDING_ID 11
#define FLAGS_BUFFER_IN_BINDING_ID 12
#define TEMP_FLAGS_BUFFER_IN_BINDING_ID 13

#define FOG_SCENE_EDGE_MIN ((-expandedMapLoadingChunks * 8 + 1) * TILE_SIZE)
#define FOG_SCENE_EDGE_MAX ((104 + expandedMapLoadingChunks * 8 - 1) * TILE_SIZE)
#define FOG_CORNER_ROUNDING 10f
#define FOG_CORNER_ROUNDING_SQUARED (FOG_CORNER_ROUNDING * FOG_CORNER_ROUNDING)

#define FIRE_CAPE 41
#define INFERNAL_CAPE 60
#define WATER 2

#define MAX_Z_HEIGHT 4 // 4 tiles high
#define BIT_ZHEIGHT 24
#define BIT_HILLSKEW 26

#define BIT_PLANE 29
#define BIT_XPOS 21
#define BIT_YPOS 13
#define BIT_ISBRIDGE 12
#define BIT_ISTERRAIN 11
#define BIT_ISDYNAMICMODEL 10

#define MAX_SHADOW_DISTANCE 100 // 100 tiles.

#define ENV_TYPE_DEFAULT 0
#define ENV_TYPE_UNDERGROUND 1

#define LIGHT_COUNT 100 // 100 lights maximum
#define LIGHT_TYPE_INVALID 0
#define LIGHT_TYPE_DIRECTIONAL 1
#define LIGHT_TYPE_POINT 2
#define LIGHT_TYPE_SPOT 3

#define LIGHT_ANIM_NONE 0
#define LIGHT_ANIM_FLICKER 1
#define LIGHT_ANIM_PULSE 2


