#define TILE_SIZE 128
#define PLANE_HEIGHT 256

#define FOG_SCENE_EDGE_MIN ((-expandedMapLoadingChunks * 8 + 1) * TILE_SIZE)
#define FOG_SCENE_EDGE_MAX ((104 + expandedMapLoadingChunks * 8 - 1) * TILE_SIZE)
#define FOG_CORNER_ROUNDING 1.5
#define FOG_CORNER_ROUNDING_SQUARED (FOG_CORNER_ROUNDING * FOG_CORNER_ROUNDING)

#define FIRE_CAPE 41
#define INFERNAL_CAPE 60

#define LIGHT_TYPE_INVALID 0
#define LIGHT_TYPE_DIRECTIONAL 1
#define LIGHT_TYPE_POINT 2
#define LIGHT_TYPE_SPOT 3

#define LIGHT_ANIM_NONE 0
#define LIGHT_ANIM_FLICKER 1
#define LIGHT_ANIM_PULSE 2
