#define FIRE_CAPE 41
#define INFERNAL_CAPE 60

#define LIGHT_TYPE_INVALID 0
#define LIGHT_TYPE_DIRECTIONAL 1
#define LIGHT_TYPE_POINT 2
#define LIGHT_TYPE_SPOT 3

#define LIGHT_ANIM_NONE 0
#define LIGHT_ANIM_FLICKER 1
#define LIGHT_ANIM_PULSE 2
